rvm:
  - 2.5.3

before_install:
  - sh sudo add-apt-repository ppa:fontforge/fontforge; sudo apt-get update; sudo apt-get install fontforge

install:
  - "travis_retry bundle install"

script: "bundle exec rspec"

gemfile:
  - Gemfile

matrix:
  fast_finish: true

sudo: false
cache: bundler
